-- Run this script in your Supabase SQL Editor to sync your schema with the application.

-- Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password_hash TEXT NOT NULL,
  balance DECIMAL(10, 2) DEFAULT 0,
  role TEXT DEFAULT 'user',
  personal_number TEXT UNIQUE,
  avatar_url TEXT,
  is_vip BOOLEAN DEFAULT false,
  is_banned BOOLEAN DEFAULT false,
  chat_blocked BOOLEAN DEFAULT false,
  blocked_until TIMESTAMPTZ,
  telegram_chat_id BIGINT UNIQUE,
  referred_by_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Vouchers Table
CREATE TABLE IF NOT EXISTS vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  max_uses INTEGER DEFAULT 1,
  used_count INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Voucher Uses Table
CREATE TABLE IF NOT EXISTS voucher_uses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT REFERENCES vouchers(id),
  user_id BIGINT REFERENCES users(id),
  used_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Offers Table
CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Subcategories Table
CREATE TABLE IF NOT EXISTS subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id),
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  parent_subcategory_id BIGINT,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Sub Sub Categories Table
CREATE TABLE IF NOT EXISTS sub_sub_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcategory_id BIGINT REFERENCES subcategories(id),
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcategory_id BIGINT REFERENCES subcategories(id),
  sub_sub_category_id BIGINT REFERENCES sub_sub_categories(id),
  name TEXT NOT NULL,
  sku TEXT,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  image_url TEXT,
  requires_input BOOLEAN DEFAULT false,
  store_type TEXT DEFAULT 'normal',
  min_quantity INTEGER DEFAULT 1,
  price_per_unit DECIMAL(10, 4),
  external_id TEXT,
  available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Payment Methods Table
CREATE TABLE IF NOT EXISTS payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  wallet_address TEXT,
  instructions TEXT,
  min_amount DECIMAL(10, 2) DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Banners Table
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  order_index INTEGER DEFAULT 0
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  payment_method_id BIGINT REFERENCES payment_methods(id),
  amount DECIMAL(10, 2) NOT NULL,
  receipt_image_url TEXT,
  note TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  total_amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'new',
  meta TEXT,
  admin_response TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  product_id BIGINT REFERENCES products(id),
  price_at_purchase DECIMAL(10, 2) NOT NULL,
  quantity INTEGER DEFAULT 1,
  extra_data TEXT
);

-- Settings Table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- User Stats Table
CREATE TABLE IF NOT EXISTS user_stats (
  user_id BIGINT PRIMARY KEY REFERENCES users(id),
  total_orders_count INTEGER DEFAULT 0,
  referral_count INTEGER DEFAULT 0,
  login_days_count INTEGER DEFAULT 0,
  last_login_date DATE,
  vouchers_redeemed_count INTEGER DEFAULT 0,
  total_recharge_sum DECIMAL(10, 2) DEFAULT 0,
  active_discount DECIMAL(10, 2) DEFAULT 0,
  has_flaming_theme BOOLEAN DEFAULT false,
  claimed_reward_index INTEGER DEFAULT -1,
  discount_expires_at TIMESTAMPTZ,
  one_product_discount_percent DECIMAL(10, 2) DEFAULT 0,
  profile_badge TEXT,
  custom_theme_color TEXT,
  has_special_support BOOLEAN DEFAULT false,
  has_priority_orders BOOLEAN DEFAULT false
);

-- Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  guest_id TEXT,
  sender_role TEXT NOT NULL,
  content TEXT,
  image_url TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily Message Counts Table
CREATE TABLE IF NOT EXISTS daily_message_counts (
  user_id BIGINT REFERENCES users(id),
  guest_id TEXT,
  date DATE DEFAULT CURRENT_DATE,
  count INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, guest_id, date)
);

-- Telegram Linking Codes Table
CREATE TABLE IF NOT EXISTS telegram_linking_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  code TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

-- Push Subscriptions Table
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  subscription TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add missing columns if tables already exist
ALTER TABLE users ADD COLUMN IF NOT EXISTS personal_number TEXT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id BIGINT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by_id BIGINT REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS chat_blocked BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked_until TIMESTAMPTZ;

ALTER TABLE categories ADD COLUMN IF NOT EXISTS special_id INTEGER;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;

ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS special_id INTEGER;
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;

ALTER TABLE products ADD COLUMN IF NOT EXISTS store_type TEXT DEFAULT 'normal';
ALTER TABLE products ADD COLUMN IF NOT EXISTS sub_sub_category_id BIGINT REFERENCES sub_sub_categories(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS min_quantity INTEGER DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_per_unit DECIMAL(10, 4);
ALTER TABLE products ADD COLUMN IF NOT EXISTS external_id TEXT;

ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS min_amount DECIMAL(10, 2) DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_response TEXT;

ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS has_flaming_theme BOOLEAN DEFAULT false;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS claimed_reward_index INTEGER DEFAULT -1;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS total_recharge_sum DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS active_discount DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS discount_expires_at TIMESTAMPTZ;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS one_product_discount_percent DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS profile_badge TEXT;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS custom_theme_color TEXT;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS has_special_support BOOLEAN DEFAULT false;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS has_priority_orders BOOLEAN DEFAULT false;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS total_orders_count INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS referral_count INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS login_days_count INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS last_login_date DATE;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS vouchers_redeemed_count INTEGER DEFAULT 0;

-- Additional Migrations
ALTER TABLE messages ADD COLUMN IF NOT EXISTS guest_id TEXT;

-- Re-create daily_message_counts if needed to update PK
DO $$ 
BEGIN 
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='daily_message_counts' AND column_name='guest_id'
    ) THEN
        DROP TABLE IF EXISTS daily_message_counts;
        CREATE TABLE daily_message_counts (
            user_id BIGINT REFERENCES users(id),
            guest_id TEXT,
            date DATE DEFAULT CURRENT_DATE,
            count INTEGER DEFAULT 0,
            PRIMARY KEY (user_id, guest_id, date)
        );
    END IF;
END $$;
